#!/bin/bash

cat /etc/passwd | grep '/home/' | \
grep -v 'cups\|syslog' | cut -d ':' -f 1 > /tmp/homes.list

mkdir /tmp/patched-acd/ -p
cd /tmp/patched-acd/
p7zip -f -k -d /tmp/patched.7z
cd -
chmod 777 -R /tmp/patched-acd/
rm -rf /tmp/patched-acd/.local/share/desktop-directories/education-Chemistry.directory
rm -rf '/tmp/patched-acd/.config/menus/applications-merged/wine-Programs-ACDLabs Freeware 2018-3D Viewer.menu'
rm -rf '/tmp/patched-acd/.config/menus/applications-merged/wine-Programs-ACDLabs Freeware 2018-ChemSketch.menu'

while read USUARIO; do
	runuser -l $USUARIO -c "rsync -a /tmp/patched-acd/ /home/$USUARIO/"
	runuser -l $USUARIO -c 'wine regedit /tmp/ACD.reg'
	
	cp /usr/share/applications/ChemSketch.desktop /home/$USUARIO/Desktop/ChemSketch.desktop

	runuser -l $USUARIO -c "rm -rf /home/$USUARIO/.cache/"
	if [ -f /usr/bin/lxpanelctl ]; then
		su - $USUARIO -c "lxpanelctl restart"
	fi
done < /tmp/homes.list